version: '3'
services:
  app:
    build: .
    container_name: "sample_active_storage_app"
    ports:
      - "3000:3000"
    command: bundle exec rails server
    volumes:
      - .:/sample_active_storage
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:5.6
    container_name: "sample_active_storage_db"
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
